---
title: "inspect_jags"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("pacman")
library(pacman)
p_load(R2jags) ; p_load(coda) ; p_load(bayesplot) ; p_load(dplyr) ; p_load(mcmcplots)
```

```{r}
#LITTLE FUNCTION SO WE CAN LOAD THE SAVED JAGS OBJECT AND CALL IT WHAT WE WANT
loadRData <- function(fileName){
#loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

#seed 13, vals 0-20:
#load("jags_output0.Rdata")
#load("jags13_0.mcmc")

output <- loadRData("jags_output0.RData") #load samples (jags object)
mc <- loadRData("jags13_0.mcmc") #load mcmc object (created from jags object)
```

```{r}
#LOOK AT IT
glimpse(output)
glimpse(mc)
summary(output)
#summary(mc) #takes forever to run

#INSPECT THE JAGS OUTPUT SHAPE A BIT MORE...:
output$parameters.to.save #the parameters we saved
#PBETA
dim(output$BUGSoutput$sims.list$pbeta) #pbeta is of the dimension 12000, 264
head(output$BUGSoutput$sims.list$pbeta) #confused - are these an estimate per chain? VERY different!

test <- output$BUGSoutput$sims.list$pbeta[,25] #just for participant 1
hist(test) #can see it's pretty uniform - a bad sign...?
density(test)$x[which(density(test)$y==max(density(test)$y))] #MAP estimate 

#THESE ARE THE NICE PLOTS, OPEN IN NEW HTML!:
mcmcplot(output)


#LOOP (SCRAPPED...)
params <- list("lambda", "gamma", "p0", "pbeta")
for (param in params) {
  print(param)
  test <- output$BUGSoutput$sims.list$param[,param] #shape: ?
  print(test)
  hist(test)
  density(test)$x[which(density(test)$y==max(density(test)$y))]
}
```
#PLOTS
```{r}
plot(output$BUGSoutput$sims.list$pbeta[,25]) #25 has clear estimate...
traceplot(output) #takes forever. GET RID OF C!

glimpse(output)
plot(output) #WHAT THE HECK IS GOING ON IN THIS PLOT???
#^^maybe shows that estimates were better for some than others
#plot(mc) #takes forever to run, uh oh...

#try this:
#posterior <- as.array(output)
#dim(posterior)

mcmc_intervals(output, pars = c("pbeta"))

par(mar=c(1,1,1,1)) #fix figure margins too large error ... NOT WORKING D:
#typed dev.off()
denplot(output)
denplot(jags13.mcmc)
```


```{r}
pp.check(x, observed, simulated, xlab='Observed data', ylab='Simulated data', 
                     main='Posterior Predictive Check', ...)
```

